name: tests

on:
    push:
    pull_request:
    schedule:
        - cron: '0 0 * * *'

jobs:
    tests:

        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                php: [7.2, 7.3, 7.4, 8.0]
                stability: [prefer-lowest, prefer-stable]

        name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, mbstring
                  tools: composer:v2
                  coverage: xdebug

            - name: Install dependencies
              run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

            - name: Run tests
              run: composer run test-ci
